### ISSUE TITLE
[5.2.1] Error: While trying to resolve module `react-native-skeleton-placeholder`

### ISSUE THREAD

**Issue by efstathiosntonas** [chramos/react-native-skeleton-placeholder#97]
After installing version `5.2.1` it throws this: 

```bash
Error: While trying to resolve module `react-native-skeleton-placeholder` from file `/Users/stathis/WebstormProjects/XXXXXX_mobile/src/components/Skeletons/ChatRoomLoadingSkeleton.tsx`, the package `/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/react-native-skeleton-placeholder/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js`. Indeed, none of these files exist:

  * /Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * /Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/node-haste/DependencyGraph.js:243:17)
    at Object.resolve (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async addDependency (/Users/stathis/WebstormProjects/XXXXXX_mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)

```

I've deleted `node_modules` and `yarn.lock`, reinstalled everything and runned `metro` with `--reset-cache` but it seems that the bundler prior releasing to npmjs created a `skeleton-placeholder.js` instead of `SkeletonPlaceholder.js` (it worked after I manually renamed the file).

**Comment by chramos** [comment]
hey @efstathiosntonas thank you,
please check the latest version `5.2.3` it should work

**Comment by efstathiosntonas** [comment]
@chramos thanks for the quick fix, everything is back to normal.
